name: QA - Pytest (Simple)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest (regression + integration)
        run: |
          mkdir -p reports
          pytest -m "regression or integration" \
                 --html=reports/report.html --self-contained-html

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pytest-html-report
          path: reports/report.html

      - name: Pull Request Creation Workflow
        uses: offensive-vk/auto-pr-action@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          title: "Automated Pull Request"
          destination-branch: "main"
          labels: "automation,enhancement"
          allow-empty: "false"
          draft: "false"
          debug: "true"
